### ISSUE TITLE
Implement deltas [epic]

### ISSUE THREAD

**Issue by eliza411** [pipeviz/pipeviz#25]
This is a prerequisite to time travel and makes sense to do in conjunction to #128 | Totally refactor interpret/transform system into something sane

There are three major steps to this: 
- [ ] Get rid of the 'orphans' system; those objects need to get first-class, persistent treatment along with all other objects.
- [ ] Define and compute deltas as part of the merge process; persist the deltas and pass them as part of the "graph update" flow within the daemon
- [ ] Update the websocket to send deltas instead of full state (except on initial send), and update the frontend to receive and incorporate the deltas appropriately.

**Related Issues:**
Concurrent work: #128 Totally refactor interpret/transform system into something sane

**Comment by sdboyer** [comment]
So, as with most internal changes, the first item - getting rid of orphans, being worked on in #228 - has thrown up an interesting barrier. I'm writing it up here both for posterity, and in the hope that writing it down helps me resolve the best course of action (as it often does).

First, there are two types of orphans - orphan vertices, and orphan edges. The former are mostly easy, but the latter are getting tricky.

The following three types show how 'orphans' are stored:

```go
// the main graph construct
type coreGraph struct {
	msgid, vserial    uint64
	vtuples 		intMapV
	orphans           edgeSpecSet // FIXME breaks immut
}

type edgeSpecSet []*veProcessingInfo

type veProcessingInfo struct {
	msgid uint64
	vt    system.VertexTuple
	uif   system.UnifyInstructionForm
	e     []system.EdgeSpec
}
```

That says: the main graph object holds a slice (an array) of `veProcessingInfo` objects, which are themselves composed of the id of the original message, the `VertexTuple` of interest, the original `uif` data produced by the message, and a slice of `EdgeSpec`s. What matters here is the final item - the EdgeSpecs. They are fundamentally different from the final form that edge data takes: `EdgeSpec` is an interface with one method, `Resolve()`, whereas the final form is a `StdEdge` - inert, logic-less data. For the most part, these `EdgeSpec`s are what give us the headache: we can no longer just store them on that orphans list, but instead have to carry them with their associated vertex itself. This will satisfy our two chief goals with this issue:

1. Stop handling orphans in a way that breaks immutability
1. Expose orphan data to frontend/clients

The difference between the `EdgeSpec` and `StdVertex` form is crucial because it is bound up with how the system defines 'equality'. Up to this point, equality (for the purposes of unification) between vertices or edges has been determined by an algorithm like this:

1. Check type equality
1. Perform some type-specific comparison (e.g., environment data is considered to refer to the same thing if the hostnames are the same).

This works well, as long as the operands to the comparison follow a simple pattern: inert data is handed to data + logic, and the latter indicates if the inert data is 'equal.' In other words, one side has to be fully inert. The issue with the orphan fixes (and letting the `EdgeSpec`s hang around) is that there is no longer any inert data for comparison.

This matters because it forces us to confront a question I'm not quite prepared for yet: which segments of logic own which types of data?

...and, I think, here's actually the eureka moment I was hoping for :) I'll have to sketch that out from my notes tomorrow, though...
